const Data = [
  {
    logo: "",
    company_name: "GLOBAL HEAVENS MB (PVT.)",
    bank_name: "Janata Bank Limited",
    location: "Local Office",
    account_number: '100240489168',
    animation: "fade-right",
  },
  {
    logo: "",
    company_name: "	M. B. INTERNATIONAL",
    bank_name: "Dutch-Bangla Bank Limited",
    location: "Nababpur Branch",
    account_number: '1041100049399',
    animation: "fade-left",
  },
  {
    logo: "",
    company_name: "	Pubali Bank Ltd",
    bank_name: "Global Heaven MB Pvt Ltd",
    location: "Bangshal Branch",
    account_number: '1804901026211',
    animation: "fade-right",
  },
  {
    logo: "",
    company_name: "First Security Islami Bank Ltd",
    bank_name: "Global Heaven MB Pvt Ltd",
    location: "Bangshal Branch",
    account_number: '010611100012263',
    animation: "fade-left",
  },
  {
    logo: "",
    company_name: "	Pubali Bank Ltd",
    bank_name: "Global Heaven MB Pvt Ltd",
    location: "Bangshal Branch",
    account_number: 1804901026211,
    animation: "fade-right",
  },
  {
    logo: "/bikash.png",
    company_name: "	",
    bank_name: "",
    location: "",
    account_number: '01885927131', 
    animation: "fade-left", 
  },
  {
    logo: "/nogod.png",
    company_name: "	",
    bank_name: "",
    location: "",
    account_number: '01885927110',
    animation: "fade-right",
  }, 
];
export default Data
